name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install lftp
        run: sudo apt-get update && sudo apt-get install -y lftp

      - name: Deploy to Hostinger
        env:
          HOSTINGER_FTP_HOST: ftp://tanbytes.com
          HOSTINGER_FTP_USERNAME: u256109075.tanbytes.com
          HOSTINGER_FTP_PASSWORD: Tan2024Bytes
        run: set ssl:verify-certificate no
             bash ./deploy.sh
